apiVersion: application.epinio.io/v1
kind: AppChart
metadata:
  namespace: {{ .Release.Namespace }}
  name: configurable-sa
  labels:
    app.kubernetes.io/component: epinio
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: epinio-app-w-serviceaccount-chart
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.image.epinio.tag }}
spec:
  shortDescription: Epinio standard deployment
  description: Epinio standard support chart for application deployment
  helmChart: {{ .Values.appChart.configurable-sa | quote }}
  settings:
    appListeningPort:
      type: 'integer'
      minimum: '0'
    serviceAccountName:
      type: 'string'
