apiVersion: v2
name: fridaybuilds-process
description: The helm chart for fridaybuilds processes to be deployed by
icon: https://raw.githubusercontent.com/epinio/helm-charts/main/assets/epinio.png
home: https://github.com/epinio/epinio
type: application
version: 0.1.29
keywords:
- epinio
- paas
maintainers:
- email: info@tashows.com
  name: Tashows
sources:
- https://github.com/Tashows/epinio-helm-charts
annotations:
  artifacthub.io/license: Apache-2.0
